# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tYnJK4BI3TkPuaiTYkILGZ7kf56y-8Ui
"""

print("Hello World!")

c=a+b
print(c)

a=7.5
b=float(input())
h=float(input())
S=h*(b/2)
print(S)

a=int(input())
b=int(input())
c=int(input())
X=(a**2+b**2-c**3)/2
print(X)

b=int(input())
a=5
p=b*a
print(p)

a=int(input())
b=int(input())
p=(a+b)**2
print(p)

a=15
b=10
c=int(input())
N=(a+b)/c
print(N)

a=int(input())
b=int(input())
q=(a**2)+(2*a*b)+(b**2)
print(f"({a}**2)+(2*{a}*{b})+({b}**2)")

a=float(input())
b=float(input())
c=float(input())
P=a+b+c
S=(P*(P-a)*(P-b)*(P-c))**0.5
print(P, S)

a=float(input())
b=float(input())
c=((a**3+14)/5)*b
print(c)

a=float(input())
n=float(input())
p=a**2//n
print(p)

a=float(int())
b=float(int())
g=a//b
print(g)

a=int(input())
b=int(input())
h=a*b
print(h)

a=int(input())
b=int(input())
d=a%b
print(d)

n=int(input())
days=n//86400
hours=n//3600
minutes=n//60
print(f"{days} дней, {hours} часов, {minutes} минут")

n=int(input())
d=int(f"{n}{n}")
h=int(f"{n}{n}{n}")
G=n+d+h
print(G)